console.log(`Nome do arquivo: `, __filename)
console.log(`diretorio do arquivo: `, __dirname)
console.log(`Parametro de execução: `,process.argv)
console.log(`ambiente do servidor `, process.platform)
//console.log(process.env)
console.log(`diretorio em que foi invocado `, process.cwd())
console.log(`sistema operacional `, process.env.OS)
console.log(`usuario no SO `, process.env.USERNAME)
console.log(`Idioma `, process.env.LANG)
console.log(`Nome do server `, process.env.COMPUTERNAME)
process.exit() //interrompe na hora todo o codigo
console.log(process.env)